services:
  redis:
    container_name: redis
    image: "redis:4.0.6-alpine"
    ports:
      - "6379:6379"
    networks:
      - postgres-network

  psql:
    container_name: psql
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: default
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  api:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - 5000:5000
    container_name: api
    env_file: .env
    volumes:
      - .:/source/:rw
    networks:
      - postgres-network
    depends_on:
      - redis
      - psql

networks:
  postgres-network:
    driver: bridge

volumes:
  db-data: